# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import typing_extensions
from ..types.media_update_response_kind import MediaUpdateResponseKind
from .media_update_response_files_item import MediaUpdateResponseFilesItemParams


class MediaUpdateResponseParams(typing_extensions.TypedDict):
    id: str
    object: str
    kind: typing_extensions.NotRequired[MediaUpdateResponseKind]
    title: typing_extensions.NotRequired[str]
    alt: typing_extensions.NotRequired[str]
    width: typing_extensions.NotRequired[int]
    height: typing_extensions.NotRequired[int]
    duration: typing_extensions.NotRequired[float]
    files: typing.Sequence[MediaUpdateResponseFilesItemParams]
    urls: typing.Dict[str, typing.Optional[typing.Any]]
    background: typing_extensions.NotRequired[str]
    metadata: typing_extensions.NotRequired[typing.Dict[str, typing.Optional[typing.Any]]]
    created: dt.datetime
    updated: dt.datetime
