# This file was auto-generated by Fern from our API Definition.

import typing

SearchGetRequestNewsDomainType = typing.Union[
    typing.Literal["Original Content", "Aggregator", "Press Releases", "Republisher", "Other"], typing.Any
]
