# This file was auto-generated by Fern from our API Definition.

import typing

from .automation_response_workflow_item_conditions import AutomationResponseWorkflowItemConditionsParams
from .automation_response_workflow_item_ref import AutomationResponseWorkflowItemRefParams

AutomationResponseWorkflowItemParams = typing.Union[
    AutomationResponseWorkflowItemRefParams, AutomationResponseWorkflowItemConditionsParams
]
