# This file was auto-generated by Fern from our API Definition.

import typing

from ..types.automation_list_response_item import AutomationListResponseItem

AutomationListResponseParams = typing.List[AutomationListResponseItem]
