# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import typing_extensions
from ..types.task_list_response_item_kind import TaskListResponseItemKind
from ..types.task_list_response_item_status import TaskListResponseItemStatus
from .task_list_response_item_results import TaskListResponseItemResultsParams


class TaskListResponseItemParams(typing_extensions.TypedDict):
    id: str
    object: str
    kind: TaskListResponseItemKind
    input: typing_extensions.NotRequired[typing.Dict[str, typing.Optional[typing.Any]]]
    options: typing_extensions.NotRequired[typing.Dict[str, typing.Optional[typing.Any]]]
    output: typing_extensions.NotRequired[typing.Dict[str, typing.Optional[typing.Any]]]
    status: TaskListResponseItemStatus
    progress: typing_extensions.NotRequired[int]
    error: typing_extensions.NotRequired[str]
    created_by: typing_extensions.NotRequired[str]
    created: dt.datetime
    updated: dt.datetime
    parent_id: typing_extensions.NotRequired[str]
    workflow: typing_extensions.NotRequired[typing.Sequence[typing.Optional[typing.Any]]]
    results: typing_extensions.NotRequired[TaskListResponseItemResultsParams]
