import os


GRAPH_CLIENT_ID = os.getenv('GRAPH_CLIENT_ID')
GRAPH_CLIENT_SECRET = os.getenv('GRAPH_CLIENT_SECRET')
GRAPH_TENANT_ID = os.getenv('GRAPH_TENANT_ID')
GRAPH_SENDER_EMAIL = os.getenv('GRAPH_SENDER_EMAIL')

