# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .token import Token


class AccountUpdaterRealTimeResponse(UniversalBaseModel):
    new_token: typing.Optional[Token] = None
    result_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The account updater result code
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
