# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .card_issuer import CardIssuer


class AdditionalCardDetails(UniversalBaseModel):
    brand: typing.Optional[str] = None
    funding: typing.Optional[str] = None
    authentication: typing.Optional[str] = None
    issuer: typing.Optional[CardIssuer] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
