# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .submerchant_authentication_response import SubmerchantAuthenticationResponse


class Authentication(UniversalBaseModel):
    threeds_cryptogram: typing.Optional[str] = None
    eci_indicator: typing.Optional[str] = None
    authentication_responses: typing.Optional[typing.List[SubmerchantAuthenticationResponse]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
