# coding: utf-8

"""
CxO Bot Automation API

 CxO Bot Automation API manages the CxO automation platform.  ## Workflows  A CxO Workflow defines the overall flow of AI automated tasks.  Conceptually, a Workflow is a sequence of steps. Those steps are defined by advanced AI units, known as Agents, and are carried out by performing detailed actions, resulting in a execution run.  ## Schedules  CxO Schedules are features allowing you to execute specific CxO Workflows at specified times or intervals.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from adomo.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_callback_auth_callback_get(self) -> None:
        """Test case for callback_auth_callback_get

        Callback
        """
        pass

    def test_callback_auth_callback_get_0(self) -> None:
        """Test case for callback_auth_callback_get_0

        Callback
        """
        pass

    def test_state_auth_callback_state_post(self) -> None:
        """Test case for state_auth_callback_state_post

        State
        """
        pass

    def test_state_auth_callback_state_post_0(self) -> None:
        """Test case for state_auth_callback_state_post_0

        State
        """
        pass


if __name__ == "__main__":
    unittest.main()
