# coding: utf-8

"""
CxO Bot Automation API

 CxO Bot Automation API manages the CxO automation platform.  ## Workflows  A CxO Workflow defines the overall flow of AI automated tasks.  Conceptually, a Workflow is a sequence of steps. Those steps are defined by advanced AI units, known as Agents, and are carried out by performing detailed actions, resulting in a execution run.  ## Schedules  CxO Schedules are features allowing you to execute specific CxO Workflows at specified times or intervals.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from adomo.models.schedule_calendar_spec import ScheduleCalendarSpec


class TestScheduleCalendarSpec(unittest.TestCase):
    """ScheduleCalendarSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScheduleCalendarSpec:
        """Test ScheduleCalendarSpec
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ScheduleCalendarSpec`
        """
        model = ScheduleCalendarSpec()
        if include_optional:
            return ScheduleCalendarSpec(
                second = [
                    adomo.models.schedule_range.ScheduleRange(
                        start = 56, 
                        end = 56, 
                        step = 56, )
                    ],
                minute = [
                    adomo.models.schedule_range.ScheduleRange(
                        start = 56, 
                        end = 56, 
                        step = 56, )
                    ],
                hour = [
                    adomo.models.schedule_range.ScheduleRange(
                        start = 56, 
                        end = 56, 
                        step = 56, )
                    ],
                day_of_month = [
                    adomo.models.schedule_range.ScheduleRange(
                        start = 56, 
                        end = 56, 
                        step = 56, )
                    ],
                month = [
                    adomo.models.schedule_range.ScheduleRange(
                        start = 56, 
                        end = 56, 
                        step = 56, )
                    ],
                year = [
                    adomo.models.schedule_range.ScheduleRange(
                        start = 56, 
                        end = 56, 
                        step = 56, )
                    ],
                day_of_week = [
                    adomo.models.schedule_range.ScheduleRange(
                        start = 56, 
                        end = 56, 
                        step = 56, )
                    ],
                comment = ''
            )
        else:
            return ScheduleCalendarSpec(
        )
        """

    def testScheduleCalendarSpec(self):
        """Test ScheduleCalendarSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
