# coding: utf-8

"""
CxO Bot Automation API

 CxO Bot Automation API manages the CxO automation platform.  ## Workflows  A CxO Workflow defines the overall flow of AI automated tasks.  Conceptually, a Workflow is a sequence of steps. Those steps are defined by advanced AI units, known as Agents, and are carried out by performing detailed actions, resulting in a execution run.  ## Schedules  CxO Schedules are features allowing you to execute specific CxO Workflows at specified times or intervals.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from adomo.api.ai_api import AiApi


class TestAiApi(unittest.TestCase):
    """AiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AiApi()

    def tearDown(self) -> None:
        pass

    def test_create_agent_ai_agents_post(self) -> None:
        """Test case for create_agent_ai_agents_post

        Create Agent
        """
        pass

    def test_get_agent_ai_agents_agent_id_get(self) -> None:
        """Test case for get_agent_ai_agents_agent_id_get

        Get Agent
        """
        pass

    def test_get_agents_ai_agents_get(self) -> None:
        """Test case for get_agents_ai_agents_get

        Get Agents
        """
        pass


if __name__ == "__main__":
    unittest.main()
