from robotooter.filters.base_filter import BaseFilter as BaseFilter

class BlankLineFilter(BaseFilter):
    def process(self, line: str) -> str | None: ...
    def finalize(self) -> str | None: ...
    def reset(self) -> None: ...
