# coding: utf-8

"""
    Electricity Maps API

    Electricity Maps API

    The version of the OpenAPI document: 1.0.0
    Contact: hello@electricitymaps.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi.api.total_load_api import TotalLoadAPI


class TestTotalLoadAPI(unittest.TestCase):
    """TotalLoadAPI unit test stubs"""

    def setUp(self) -> None:
        self.api = TotalLoadAPI()

    def tearDown(self) -> None:
        pass

    def test_get_total_load_forecast(self) -> None:
        """Test case for get_total_load_forecast

        Total Load Forecast
        """
        pass

    def test_get_total_load_history(self) -> None:
        """Test case for get_total_load_history

        Total Load History
        """
        pass

    def test_get_total_load_latest(self) -> None:
        """Test case for get_total_load_latest

        Total Load Latest
        """
        pass

    def test_get_total_load_past(self) -> None:
        """Test case for get_total_load_past

        Total Load Past
        """
        pass

    def test_get_total_load_past_range(self) -> None:
        """Test case for get_total_load_past_range

        Total Load Past Range
        """
        pass


if __name__ == '__main__':
    unittest.main()
