# coding: utf-8

"""
    Electricity Maps API

    Electricity Maps API

    The version of the OpenAPI document: 1.0.0
    Contact: hello@electricitymaps.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi.models.past_range_query import PastRangeQuery

class TestPastRangeQuery(unittest.TestCase):
    """PastRangeQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PastRangeQuery:
        """Test PastRangeQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PastRangeQuery`
        """
        model = PastRangeQuery()
        if include_optional:
            return PastRangeQuery(
                start = '2024-05-19T03:00:00',
                end = '2024-05-19T08:00:00',
                temporal_granularity = '15_minutes',
                zone_key = 'DK-DK2',
                lat = -88.0703,
                lon = 41.877,
                data_center_provider = 'gcp',
                data_center_region = 'us-central1',
                disable_caller_lookup = 'false',
                disable_estimations = 'false',
                emission_factor_type = 'direct'
            )
        else:
            return PastRangeQuery(
                start = '2024-05-19T03:00:00',
                end = '2024-05-19T08:00:00',
        )
        """

    def testPastRangeQuery(self):
        """Test PastRangeQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
