# coding: utf-8

"""
    Electricity Maps API

    Electricity Maps API

    The version of the OpenAPI document: 1.0.0
    Contact: hello@electricitymaps.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi.api.default_api import DefaultAPI


class TestDefaultAPI(unittest.TestCase):
    """DefaultAPI unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultAPI()

    def tearDown(self) -> None:
        pass

    def test_get_zones(self) -> None:
        """Test case for get_zones

        Zones
        """
        pass

    def test_optimize_consumption(self) -> None:
        """Test case for optimize_consumption

        Optimize Consumption
        """
        pass


if __name__ == '__main__':
    unittest.main()
