#
# Autogenerated by Thrift Compiler (0.16.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:no_utf8strings
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

from .ttypes import *
NUM_NODES_ALL = 0
NUM_NODES_ALL_RACKS = -1
MAX_FRAGMENT_INSTANCES_PER_NODE = 128
MIN_HASH_TBL_MEM = 10485760
