{
 "title": "EFC",
 "description": "EFC Rest Check metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "label": "bucket", "query": { "query": "buckets()" } },
   { "name": "influxdata", "label": "influxdata", "query": "influxdb" },
   { "name": "promdata", "label": "promdata", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Storage Usage",
   "type": "gauge",
   "description": "% of used space from Opensearch data nodes",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{cluster=\"efc-prod\", namespace=\"opensearch\", persistentvolumeclaim=~\"data-opensearch-nodes.*\"}) by (pods) / \nsum(kubelet_volume_stats_capacity_bytes{namespace=\"opensearch\", persistentvolumeclaim=~\"data-opensearch-nodes.*\"}) by (pods) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Capacity",
   "type": "bargauge",
   "description": "Storage Capacity from Opensearch data nodes pvc.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "TB" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{cluster=\"efc-prod\", namespace=\"opensearch\", persistentvolumeclaim=~\"data-opensearch-nodes.*\"}) by (pods) / (1000^4)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Integrations",
   "type": "timeseries",
   "description": "Total of backlogged Integration events captured every 5 minutes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stream\")\n  |> filter(fn: (r) => r[\"_field\"] == \"integrationevents\")\n  |> aggregateWindow(every: 5m, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Enrichments",
   "type": "timeseries",
   "description": "Total of backlogged Enrichments captured every 5 minutes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stream\")\n  |> filter(fn: (r) => r[\"_field\"] == \"enrichmentevents\")\n  |> aggregateWindow(every: 5m, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "OpenSearch",
   "type": "timeseries",
   "description": "Total of backlogged Bulk events captured every 5 minutes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stream\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bulkevents\")\n  |> aggregateWindow(every: 5m, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Rules",
   "type": "timeseries",
   "description": "Total of backlogged Rules captured every 5 minutes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stream\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ruleevents\")\n  |> aggregateWindow(every: 5m, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  }
 ]
}