from typing import Literal

type TBibTeXEntryType = Literal[
    "article",
    "book",
    "incollection",
    "inproceedings",
    "mastersthesis",
    "misc",
    "phdthesis",
    "proceedings",
    "techreport",
    "unpublished",
    "UNKNOWN",
]

type TBasicPubState = Literal[
    "",
    "unpub",
    "forthcoming",
]

type TPubState = Literal[
    TBasicPubState,
    "inwork",
    "submitted",
    "published",
]

type TLanguageID = Literal[
    "",
    "catalan",
    "czech",
    "danish",
    "dutch",
    "english",
    "french",
    "greek",
    "italian",
    "latin",
    "lithuanian",
    "ngerman",
    "polish",
    "portuguese",
    "romanian",
    "russian",
    "slovak",
    "spanish",
    "swedish",
    "unknown",
]

type TEpoch = Literal[
    "",
    "ancient-philosophy",
    "ancient-scientists",
    "austrian-philosophy",
    "british-idealism",
    "classics",
    "contemporaries",
    "contemporary-scientists",
    "continental-philosophy",
    "critical-theory",
    "cynics",
    "enlightenment",
    "existentialism",
    "exotic-philosophy",
    "german-idealism",
    "german-rationalism",
    "gestalt-psychology",
    "hermeneutics",
    "islamic-philosophy",
    "mathematicians",
    "medieval-philosophy",
    "modern-philosophy",
    "modern-scientists",
    "neokantianism",
    "neo-kantianism",
    "neoplatonism",
    "new-realism",
    "ordinary-language-philosophy",
    "phenomenology",
    "polish-logic",
    "pragmatism",
    "presocratics",
    "renaissance",
    "stoics",
    "theologians",
    "vienna-circle",
]
