# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.automations_create_request_workflow_item_kind import AutomationsCreateRequestWorkflowItemKind
from .automations_create_request_workflow_item_next_item import AutomationsCreateRequestWorkflowItemNextItemParams


class AutomationsCreateRequestWorkflowItemParams(typing_extensions.TypedDict):
    kind: AutomationsCreateRequestWorkflowItemKind
    ref: typing_extensions.NotRequired[str]
    next: typing_extensions.NotRequired[typing.Sequence[AutomationsCreateRequestWorkflowItemNextItemParams]]
