# Generated by Django 5.2.4 on 2025-08-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spodcat', '0006_season_to_season2'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='name'),
        ),
    ]
