# coding: utf-8

"""
    BriefcaseBrain API

    Official API for BriefcaseBrain Legal AI Platform

    The version of the OpenAPI document: 1.0.0
    Contact: support@briefcasebrain.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from briefcasebrain_sdk.api.queries_api import QueriesApi


class TestQueriesApi(unittest.TestCase):
    """QueriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QueriesApi()

    def tearDown(self) -> None:
        pass

    def test_api_queries_get(self) -> None:
        """Test case for api_queries_get

        Get saved queries
        """
        pass

    def test_api_queries_post(self) -> None:
        """Test case for api_queries_post

        Save a query
        """
        pass


if __name__ == '__main__':
    unittest.main()
