# coding: utf-8

"""
    BriefcaseBrain API

    Official API for BriefcaseBrain Legal AI Platform

    The version of the OpenAPI document: 1.0.0
    Contact: support@briefcasebrain.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from briefcasebrain_sdk.models.enhance_query_request import EnhanceQueryRequest

class TestEnhanceQueryRequest(unittest.TestCase):
    """EnhanceQueryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnhanceQueryRequest:
        """Test EnhanceQueryRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnhanceQueryRequest`
        """
        model = EnhanceQueryRequest()
        if include_optional:
            return EnhanceQueryRequest(
                query = '',
                selected_enhancements = [
                    ''
                    ],
                practice_area = ''
            )
        else:
            return EnhanceQueryRequest(
                query = '',
        )
        """

    def testEnhanceQueryRequest(self):
        """Test EnhanceQueryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
