# coding: utf-8

"""
    BriefcaseBrain API

    Official API for BriefcaseBrain Legal AI Platform

    The version of the OpenAPI document: 1.0.0
    Contact: support@briefcasebrain.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from briefcasebrain_sdk.api.workflows_api import WorkflowsApi


class TestWorkflowsApi(unittest.TestCase):
    """WorkflowsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkflowsApi()

    def tearDown(self) -> None:
        pass

    def test_api_workflows_get(self) -> None:
        """Test case for api_workflows_get

        List workflows
        """
        pass

    def test_api_workflows_post(self) -> None:
        """Test case for api_workflows_post

        Create workflow
        """
        pass


if __name__ == '__main__':
    unittest.main()
