# coding: utf-8

"""
    BriefcaseBrain API

    Official API for BriefcaseBrain Legal AI Platform

    The version of the OpenAPI document: 1.0.0
    Contact: support@briefcasebrain.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from briefcasebrain_sdk.models.api_user_credits_get200_response import ApiUserCreditsGet200Response

class TestApiUserCreditsGet200Response(unittest.TestCase):
    """ApiUserCreditsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiUserCreditsGet200Response:
        """Test ApiUserCreditsGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiUserCreditsGet200Response`
        """
        model = ApiUserCreditsGet200Response()
        if include_optional:
            return ApiUserCreditsGet200Response(
                credits = 56,
                usage = 56,
                limit = 56
            )
        else:
            return ApiUserCreditsGet200Response(
        )
        """

    def testApiUserCreditsGet200Response(self):
        """Test ApiUserCreditsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
