# coding: utf-8

# flake8: noqa

"""
CxO Bot Automation API

 CxO Bot Automation API manages the CxO automation platform.  ## Workflows  A CxO Workflow defines the overall flow of AI automated tasks.  Conceptually, a Workflow is a sequence of steps. Those steps are defined by advanced AI units, known as Agents, and are carried out by performing detailed actions, resulting in a execution run.  ## Schedules  CxO Schedules are features allowing you to execute specific CxO Workflows at specified times or intervals.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ActivitiesApi",
    "AiApi",
    "ApiServiceApi",
    "AuthApi",
    "GraphqlApi",
    "IntegrationsApi",
    "JobsApi",
    "SchedulesApi",
    "UsersApi",
    "WorkflowsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ActivityInput",
    "ActivityInvocationInput",
    "ActivityInvocationOutput",
    "ActivityOutput",
    "ActivityState",
    "ActivityStatementInput",
    "ActivityStatementOutput",
    "AgentConfigInput",
    "AgentConfigInputMcpServersValue",
    "AgentConfigOutput",
    "Attribute",
    "BackfillRequest",
    "ChildWorkflowInvocationInput",
    "ChildWorkflowInvocationOutput",
    "ChildWorkflowStatementInput",
    "ChildWorkflowStatementOutput",
    "Command",
    "ConditionInvocationInput",
    "ConditionInvocationOutput",
    "ConditionStatementInput",
    "ConditionStatementOutput",
    "CreateScheduleRequest",
    "Cwd",
    "Dependency",
    "Dsl",
    "ExecutionStatus",
    "FieldType",
    "Group",
    "HTTPValidationError",
    "HealthResponse",
    "HealthStatus",
    "HistoryEventResponse",
    "JSONValue",
    "JobResponse",
    "JobsResponse",
    "JobsSortOn",
    "McpImageConfig",
    "McpSseConfig",
    "McpStdioConfig",
    "ModelField",
    "ModelSchema",
    "OutputFormat",
    "OutputFormatType",
    "PageInfo",
    "PageSize",
    "ParallelInput",
    "ParallelInputBranchesInner",
    "ParallelOutput",
    "ParallelOutputBranchesInner",
    "ParallelStatementInput",
    "ParallelStatementOutput",
    "QueryResponse",
    "Response",
    "Result",
    "Root",
    "Schedule",
    "ScheduleActionExecutionStartWorkflow",
    "ScheduleActionExecutionStartWorkflowModel",
    "ScheduleActionResult",
    "ScheduleActionResultModel",
    "ScheduleActionStartWorkflowModel",
    "ScheduleCalendarSpec",
    "ScheduleDescription",
    "ScheduleInfo",
    "ScheduleIntervalSpec",
    "ScheduleListActionStartWorkflow",
    "ScheduleListDescription",
    "ScheduleListInfo",
    "ScheduleListSchedule",
    "SchedulePolicyModel",
    "ScheduleRange",
    "ScheduleSpecInput",
    "ScheduleSpecOutput",
    "ScheduleStateModel",
    "SecretsValue",
    "SequenceInput",
    "SequenceOutput",
    "SequenceStatementInput",
    "SequenceStatementOutput",
    "Signal",
    "SleepInvocationInput",
    "SleepInvocationOutput",
    "SleepStatementInput",
    "SleepStatementOutput",
    "SortDirection",
    "StartWorkflowExecutionRequest",
    "StartWorkflowExecutionResponse",
    "StateInput",
    "SystemPrompt",
    "Timeout",
    "TriggerScheduleRequest",
    "Update",
    "UpdateResponse",
    "UpdateScheduleRequest",
    "User",
    "ValidationError",
    "ValidationErrorLocInner",
    "WidgetType",
    "WorkflowInput",
    "WorkflowOutput",
    "WorkflowState",
]

# import apis into sdk package
from adomo.api.activities_api import ActivitiesApi as ActivitiesApi
from adomo.api.ai_api import AiApi as AiApi
from adomo.api.api_service_api import ApiServiceApi as ApiServiceApi
from adomo.api.auth_api import AuthApi as AuthApi
from adomo.api.graphql_api import GraphqlApi as GraphqlApi
from adomo.api.integrations_api import IntegrationsApi as IntegrationsApi
from adomo.api.jobs_api import JobsApi as JobsApi
from adomo.api.schedules_api import SchedulesApi as SchedulesApi
from adomo.api.users_api import UsersApi as UsersApi
from adomo.api.workflows_api import WorkflowsApi as WorkflowsApi

# import ApiClient
from adomo.api_response import ApiResponse as ApiResponse
from adomo.api_client import ApiClient as ApiClient
from adomo.configuration import Configuration as Configuration
from adomo.exceptions import OpenApiException as OpenApiException
from adomo.exceptions import ApiTypeError as ApiTypeError
from adomo.exceptions import ApiValueError as ApiValueError
from adomo.exceptions import ApiKeyError as ApiKeyError
from adomo.exceptions import ApiAttributeError as ApiAttributeError
from adomo.exceptions import ApiException as ApiException

# import models into sdk package
from adomo.models.activity_input import ActivityInput as ActivityInput
from adomo.models.activity_invocation_input import (
    ActivityInvocationInput as ActivityInvocationInput,
)
from adomo.models.activity_invocation_output import (
    ActivityInvocationOutput as ActivityInvocationOutput,
)
from adomo.models.activity_output import ActivityOutput as ActivityOutput
from adomo.models.activity_state import ActivityState as ActivityState
from adomo.models.activity_statement_input import (
    ActivityStatementInput as ActivityStatementInput,
)
from adomo.models.activity_statement_output import (
    ActivityStatementOutput as ActivityStatementOutput,
)
from adomo.models.agent_config_input import AgentConfigInput as AgentConfigInput
from adomo.models.agent_config_input_mcp_servers_value import (
    AgentConfigInputMcpServersValue as AgentConfigInputMcpServersValue,
)
from adomo.models.agent_config_output import AgentConfigOutput as AgentConfigOutput
from adomo.models.attribute import Attribute as Attribute
from adomo.models.backfill_request import BackfillRequest as BackfillRequest
from adomo.models.child_workflow_invocation_input import (
    ChildWorkflowInvocationInput as ChildWorkflowInvocationInput,
)
from adomo.models.child_workflow_invocation_output import (
    ChildWorkflowInvocationOutput as ChildWorkflowInvocationOutput,
)
from adomo.models.child_workflow_statement_input import (
    ChildWorkflowStatementInput as ChildWorkflowStatementInput,
)
from adomo.models.child_workflow_statement_output import (
    ChildWorkflowStatementOutput as ChildWorkflowStatementOutput,
)
from adomo.models.command import Command as Command
from adomo.models.condition_invocation_input import (
    ConditionInvocationInput as ConditionInvocationInput,
)
from adomo.models.condition_invocation_output import (
    ConditionInvocationOutput as ConditionInvocationOutput,
)
from adomo.models.condition_statement_input import (
    ConditionStatementInput as ConditionStatementInput,
)
from adomo.models.condition_statement_output import (
    ConditionStatementOutput as ConditionStatementOutput,
)
from adomo.models.create_schedule_request import (
    CreateScheduleRequest as CreateScheduleRequest,
)
from adomo.models.cwd import Cwd as Cwd
from adomo.models.dependency import Dependency as Dependency
from adomo.models.dsl import Dsl as Dsl
from adomo.models.execution_status import ExecutionStatus as ExecutionStatus
from adomo.models.field_type import FieldType as FieldType
from adomo.models.group import Group as Group
from adomo.models.http_validation_error import (
    HTTPValidationError as HTTPValidationError,
)
from adomo.models.health_response import HealthResponse as HealthResponse
from adomo.models.health_status import HealthStatus as HealthStatus
from adomo.models.history_event_response import (
    HistoryEventResponse as HistoryEventResponse,
)
from adomo.models.json_value import JSONValue as JSONValue
from adomo.models.job_response import JobResponse as JobResponse
from adomo.models.jobs_response import JobsResponse as JobsResponse
from adomo.models.jobs_sort_on import JobsSortOn as JobsSortOn
from adomo.models.mcp_image_config import McpImageConfig as McpImageConfig
from adomo.models.mcp_sse_config import McpSseConfig as McpSseConfig
from adomo.models.mcp_stdio_config import McpStdioConfig as McpStdioConfig
from adomo.models.model_field import ModelField as ModelField
from adomo.models.model_schema import ModelSchema as ModelSchema
from adomo.models.output_format import OutputFormat as OutputFormat
from adomo.models.output_format_type import OutputFormatType as OutputFormatType
from adomo.models.page_info import PageInfo as PageInfo
from adomo.models.page_size import PageSize as PageSize
from adomo.models.parallel_input import ParallelInput as ParallelInput
from adomo.models.parallel_input_branches_inner import (
    ParallelInputBranchesInner as ParallelInputBranchesInner,
)
from adomo.models.parallel_output import ParallelOutput as ParallelOutput
from adomo.models.parallel_output_branches_inner import (
    ParallelOutputBranchesInner as ParallelOutputBranchesInner,
)
from adomo.models.parallel_statement_input import (
    ParallelStatementInput as ParallelStatementInput,
)
from adomo.models.parallel_statement_output import (
    ParallelStatementOutput as ParallelStatementOutput,
)
from adomo.models.query_response import QueryResponse as QueryResponse
from adomo.models.response import Response as Response
from adomo.models.result import Result as Result
from adomo.models.root import Root as Root
from adomo.models.schedule import Schedule as Schedule
from adomo.models.schedule_action_execution_start_workflow import (
    ScheduleActionExecutionStartWorkflow as ScheduleActionExecutionStartWorkflow,
)
from adomo.models.schedule_action_execution_start_workflow_model import (
    ScheduleActionExecutionStartWorkflowModel as ScheduleActionExecutionStartWorkflowModel,
)
from adomo.models.schedule_action_result import (
    ScheduleActionResult as ScheduleActionResult,
)
from adomo.models.schedule_action_result_model import (
    ScheduleActionResultModel as ScheduleActionResultModel,
)
from adomo.models.schedule_action_start_workflow_model import (
    ScheduleActionStartWorkflowModel as ScheduleActionStartWorkflowModel,
)
from adomo.models.schedule_calendar_spec import (
    ScheduleCalendarSpec as ScheduleCalendarSpec,
)
from adomo.models.schedule_description import ScheduleDescription as ScheduleDescription
from adomo.models.schedule_info import ScheduleInfo as ScheduleInfo
from adomo.models.schedule_interval_spec import (
    ScheduleIntervalSpec as ScheduleIntervalSpec,
)
from adomo.models.schedule_list_action_start_workflow import (
    ScheduleListActionStartWorkflow as ScheduleListActionStartWorkflow,
)
from adomo.models.schedule_list_description import (
    ScheduleListDescription as ScheduleListDescription,
)
from adomo.models.schedule_list_info import ScheduleListInfo as ScheduleListInfo
from adomo.models.schedule_list_schedule import (
    ScheduleListSchedule as ScheduleListSchedule,
)
from adomo.models.schedule_policy_model import (
    SchedulePolicyModel as SchedulePolicyModel,
)
from adomo.models.schedule_range import ScheduleRange as ScheduleRange
from adomo.models.schedule_spec_input import ScheduleSpecInput as ScheduleSpecInput
from adomo.models.schedule_spec_output import ScheduleSpecOutput as ScheduleSpecOutput
from adomo.models.schedule_state_model import ScheduleStateModel as ScheduleStateModel
from adomo.models.secrets_value import SecretsValue as SecretsValue
from adomo.models.sequence_input import SequenceInput as SequenceInput
from adomo.models.sequence_output import SequenceOutput as SequenceOutput
from adomo.models.sequence_statement_input import (
    SequenceStatementInput as SequenceStatementInput,
)
from adomo.models.sequence_statement_output import (
    SequenceStatementOutput as SequenceStatementOutput,
)
from adomo.models.signal import Signal as Signal
from adomo.models.sleep_invocation_input import (
    SleepInvocationInput as SleepInvocationInput,
)
from adomo.models.sleep_invocation_output import (
    SleepInvocationOutput as SleepInvocationOutput,
)
from adomo.models.sleep_statement_input import (
    SleepStatementInput as SleepStatementInput,
)
from adomo.models.sleep_statement_output import (
    SleepStatementOutput as SleepStatementOutput,
)
from adomo.models.sort_direction import SortDirection as SortDirection
from adomo.models.start_workflow_execution_request import (
    StartWorkflowExecutionRequest as StartWorkflowExecutionRequest,
)
from adomo.models.start_workflow_execution_response import (
    StartWorkflowExecutionResponse as StartWorkflowExecutionResponse,
)
from adomo.models.state_input import StateInput as StateInput
from adomo.models.system_prompt import SystemPrompt as SystemPrompt
from adomo.models.timeout import Timeout as Timeout
from adomo.models.trigger_schedule_request import (
    TriggerScheduleRequest as TriggerScheduleRequest,
)
from adomo.models.update import Update as Update
from adomo.models.update_response import UpdateResponse as UpdateResponse
from adomo.models.update_schedule_request import (
    UpdateScheduleRequest as UpdateScheduleRequest,
)
from adomo.models.user import User as User
from adomo.models.validation_error import ValidationError as ValidationError
from adomo.models.validation_error_loc_inner import (
    ValidationErrorLocInner as ValidationErrorLocInner,
)
from adomo.models.widget_type import WidgetType as WidgetType
from adomo.models.workflow_input import WorkflowInput as WorkflowInput
from adomo.models.workflow_output import WorkflowOutput as WorkflowOutput
from adomo.models.workflow_state import WorkflowState as WorkflowState


from lazy_imports import LazyModule, as_package, load

load(
    LazyModule(
        *as_package(__file__),
        ("__version__", __version__),
        ("__all__", __all__),
        """# import apis into sdk package
from adomo.api.activities_api import ActivitiesApi as ActivitiesApi
from adomo.api.ai_api import AiApi as AiApi
from adomo.api.api_service_api import ApiServiceApi as ApiServiceApi
from adomo.api.auth_api import AuthApi as AuthApi
from adomo.api.graphql_api import GraphqlApi as GraphqlApi
from adomo.api.integrations_api import IntegrationsApi as IntegrationsApi
from adomo.api.jobs_api import JobsApi as JobsApi
from adomo.api.schedules_api import SchedulesApi as SchedulesApi
from adomo.api.users_api import UsersApi as UsersApi
from adomo.api.workflows_api import WorkflowsApi as WorkflowsApi

# import ApiClient
from adomo.api_response import ApiResponse as ApiResponse
from adomo.api_client import ApiClient as ApiClient
from adomo.configuration import Configuration as Configuration
from adomo.exceptions import OpenApiException as OpenApiException
from adomo.exceptions import ApiTypeError as ApiTypeError
from adomo.exceptions import ApiValueError as ApiValueError
from adomo.exceptions import ApiKeyError as ApiKeyError
from adomo.exceptions import ApiAttributeError as ApiAttributeError
from adomo.exceptions import ApiException as ApiException

# import models into sdk package
from adomo.models.activity_input import ActivityInput as ActivityInput
from adomo.models.activity_invocation_input import ActivityInvocationInput as ActivityInvocationInput
from adomo.models.activity_invocation_output import ActivityInvocationOutput as ActivityInvocationOutput
from adomo.models.activity_output import ActivityOutput as ActivityOutput
from adomo.models.activity_state import ActivityState as ActivityState
from adomo.models.activity_statement_input import ActivityStatementInput as ActivityStatementInput
from adomo.models.activity_statement_output import ActivityStatementOutput as ActivityStatementOutput
from adomo.models.agent_config_input import AgentConfigInput as AgentConfigInput
from adomo.models.agent_config_input_mcp_servers_value import AgentConfigInputMcpServersValue as AgentConfigInputMcpServersValue
from adomo.models.agent_config_output import AgentConfigOutput as AgentConfigOutput
from adomo.models.attribute import Attribute as Attribute
from adomo.models.backfill_request import BackfillRequest as BackfillRequest
from adomo.models.child_workflow_invocation_input import ChildWorkflowInvocationInput as ChildWorkflowInvocationInput
from adomo.models.child_workflow_invocation_output import ChildWorkflowInvocationOutput as ChildWorkflowInvocationOutput
from adomo.models.child_workflow_statement_input import ChildWorkflowStatementInput as ChildWorkflowStatementInput
from adomo.models.child_workflow_statement_output import ChildWorkflowStatementOutput as ChildWorkflowStatementOutput
from adomo.models.command import Command as Command
from adomo.models.condition_invocation_input import ConditionInvocationInput as ConditionInvocationInput
from adomo.models.condition_invocation_output import ConditionInvocationOutput as ConditionInvocationOutput
from adomo.models.condition_statement_input import ConditionStatementInput as ConditionStatementInput
from adomo.models.condition_statement_output import ConditionStatementOutput as ConditionStatementOutput
from adomo.models.create_schedule_request import CreateScheduleRequest as CreateScheduleRequest
from adomo.models.cwd import Cwd as Cwd
from adomo.models.dependency import Dependency as Dependency
from adomo.models.dsl import Dsl as Dsl
from adomo.models.execution_status import ExecutionStatus as ExecutionStatus
from adomo.models.field_type import FieldType as FieldType
from adomo.models.group import Group as Group
from adomo.models.http_validation_error import HTTPValidationError as HTTPValidationError
from adomo.models.health_response import HealthResponse as HealthResponse
from adomo.models.health_status import HealthStatus as HealthStatus
from adomo.models.history_event_response import HistoryEventResponse as HistoryEventResponse
from adomo.models.json_value import JSONValue as JSONValue
from adomo.models.job_response import JobResponse as JobResponse
from adomo.models.jobs_response import JobsResponse as JobsResponse
from adomo.models.jobs_sort_on import JobsSortOn as JobsSortOn
from adomo.models.mcp_image_config import McpImageConfig as McpImageConfig
from adomo.models.mcp_sse_config import McpSseConfig as McpSseConfig
from adomo.models.mcp_stdio_config import McpStdioConfig as McpStdioConfig
from adomo.models.model_field import ModelField as ModelField
from adomo.models.model_schema import ModelSchema as ModelSchema
from adomo.models.output_format import OutputFormat as OutputFormat
from adomo.models.output_format_type import OutputFormatType as OutputFormatType
from adomo.models.page_info import PageInfo as PageInfo
from adomo.models.page_size import PageSize as PageSize
from adomo.models.parallel_input import ParallelInput as ParallelInput
from adomo.models.parallel_input_branches_inner import ParallelInputBranchesInner as ParallelInputBranchesInner
from adomo.models.parallel_output import ParallelOutput as ParallelOutput
from adomo.models.parallel_output_branches_inner import ParallelOutputBranchesInner as ParallelOutputBranchesInner
from adomo.models.parallel_statement_input import ParallelStatementInput as ParallelStatementInput
from adomo.models.parallel_statement_output import ParallelStatementOutput as ParallelStatementOutput
from adomo.models.query_response import QueryResponse as QueryResponse
from adomo.models.response import Response as Response
from adomo.models.result import Result as Result
from adomo.models.root import Root as Root
from adomo.models.schedule import Schedule as Schedule
from adomo.models.schedule_action_execution_start_workflow import ScheduleActionExecutionStartWorkflow as ScheduleActionExecutionStartWorkflow
from adomo.models.schedule_action_execution_start_workflow_model import ScheduleActionExecutionStartWorkflowModel as ScheduleActionExecutionStartWorkflowModel
from adomo.models.schedule_action_result import ScheduleActionResult as ScheduleActionResult
from adomo.models.schedule_action_result_model import ScheduleActionResultModel as ScheduleActionResultModel
from adomo.models.schedule_action_start_workflow_model import ScheduleActionStartWorkflowModel as ScheduleActionStartWorkflowModel
from adomo.models.schedule_calendar_spec import ScheduleCalendarSpec as ScheduleCalendarSpec
from adomo.models.schedule_description import ScheduleDescription as ScheduleDescription
from adomo.models.schedule_info import ScheduleInfo as ScheduleInfo
from adomo.models.schedule_interval_spec import ScheduleIntervalSpec as ScheduleIntervalSpec
from adomo.models.schedule_list_action_start_workflow import ScheduleListActionStartWorkflow as ScheduleListActionStartWorkflow
from adomo.models.schedule_list_description import ScheduleListDescription as ScheduleListDescription
from adomo.models.schedule_list_info import ScheduleListInfo as ScheduleListInfo
from adomo.models.schedule_list_schedule import ScheduleListSchedule as ScheduleListSchedule
from adomo.models.schedule_policy_model import SchedulePolicyModel as SchedulePolicyModel
from adomo.models.schedule_range import ScheduleRange as ScheduleRange
from adomo.models.schedule_spec_input import ScheduleSpecInput as ScheduleSpecInput
from adomo.models.schedule_spec_output import ScheduleSpecOutput as ScheduleSpecOutput
from adomo.models.schedule_state_model import ScheduleStateModel as ScheduleStateModel
from adomo.models.secrets_value import SecretsValue as SecretsValue
from adomo.models.sequence_input import SequenceInput as SequenceInput
from adomo.models.sequence_output import SequenceOutput as SequenceOutput
from adomo.models.sequence_statement_input import SequenceStatementInput as SequenceStatementInput
from adomo.models.sequence_statement_output import SequenceStatementOutput as SequenceStatementOutput
from adomo.models.signal import Signal as Signal
from adomo.models.sleep_invocation_input import SleepInvocationInput as SleepInvocationInput
from adomo.models.sleep_invocation_output import SleepInvocationOutput as SleepInvocationOutput
from adomo.models.sleep_statement_input import SleepStatementInput as SleepStatementInput
from adomo.models.sleep_statement_output import SleepStatementOutput as SleepStatementOutput
from adomo.models.sort_direction import SortDirection as SortDirection
from adomo.models.start_workflow_execution_request import StartWorkflowExecutionRequest as StartWorkflowExecutionRequest
from adomo.models.start_workflow_execution_response import StartWorkflowExecutionResponse as StartWorkflowExecutionResponse
from adomo.models.state_input import StateInput as StateInput
from adomo.models.system_prompt import SystemPrompt as SystemPrompt
from adomo.models.timeout import Timeout as Timeout
from adomo.models.trigger_schedule_request import TriggerScheduleRequest as TriggerScheduleRequest
from adomo.models.update import Update as Update
from adomo.models.update_response import UpdateResponse as UpdateResponse
from adomo.models.update_schedule_request import UpdateScheduleRequest as UpdateScheduleRequest
from adomo.models.user import User as User
from adomo.models.validation_error import ValidationError as ValidationError
from adomo.models.validation_error_loc_inner import ValidationErrorLocInner as ValidationErrorLocInner
from adomo.models.widget_type import WidgetType as WidgetType
from adomo.models.workflow_input import WorkflowInput as WorkflowInput
from adomo.models.workflow_output import WorkflowOutput as WorkflowOutput
from adomo.models.workflow_state import WorkflowState as WorkflowState

""",
        name=__name__,
        doc=__doc__,
    )
)
