# interfaces/env_handler_interface.py
from typing import Protocol

class IEnvHandler(Protocol):
    def val_str(self, value) -> None: ...
    def is_value_null_or_empty(self, value) -> None: ...
    def get_env_value(self, msg: str) -> None: ...
    def set_logger(self, logger) -> None: ...
