# Generated via: macrotype macrotype
# Do not edit by hand
from __future__ import annotations

from typing import Any

from macrotype.types.ir import Ty, TyRoot

annotations = annotations

def unparse(t: Ty) -> Any: ...
def unparse_top(root: TyRoot) -> Any: ...
def _apply_annos(inner: Any, tree) -> Any: ...
def _unparse(n: Ty) -> Any: ...
def _unparse_no_annos(n: Ty) -> Any: ...
