
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-08-22T11:13:15+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "a5b452b5f1ac259cd32861a8181e4b4e0ea0f136",
 "version": "1.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
