# Generated via: macrotype macrotype/modules/transformers/recover_custom_generics.py -o __macrotype__/macrotype/modules/transformers/recover_custom_generics.pyi
# Do not edit by hand
from __future__ import annotations

from ast import Module
from typing import Any

from macrotype.modules.ir import ModuleDecl

def _has_custom_class_getitem(obj: object) -> bool: ...
def _needs_recover(obj: object) -> bool: ...
def _build_maps(tree: Module, code: str): ...
def _apply_recover(
    site, expr: None | str, name: str, glb: dict[str, Any], lcl: None | dict[str, Any]
) -> None: ...
def recover_custom_generics(mi: ModuleDecl) -> None: ...
