# Generated via: macrotype macrotype
# Do not edit by hand
from macrotype.modules.ir import Decl, ModuleDecl

def _transform_decls(decls: list[Decl]) -> list[Decl]: ...
def transform_newtypes(mi: ModuleDecl) -> None: ...
