# Generated via: macrotype macrotype/modules/transformers/overload.py -o __macrotype__/macrotype/modules/transformers/overload.pyi
# Do not edit by hand
from typing import Any, Callable

from macrotype.meta_types import get_overloads
from macrotype.modules.ir import ClassDecl, FuncDecl, ModuleDecl

_get_overloads = get_overloads

def _annotation_for_value(value: Any) -> Any: ...
def _make_literal_overload(fn: Callable, args: tuple, kwargs: dict, result: Any) -> Callable: ...
def _expand_function(fn: Callable, sym: FuncDecl) -> list[FuncDecl]: ...
def _get_function(sym: FuncDecl) -> Callable | None: ...
def _transform_class(sym: ClassDecl) -> None: ...
def expand_overloads(mi: ModuleDecl) -> None: ...
