"""
Comprehensive timezone offset mappings for all timezones found in cities15000.txt
"""

def get_comprehensive_timezone_offsets():
    """Get comprehensive timezone offset mapping."""
    return {
        # Africa
        'Africa/Abidjan': '+0:00',        # GMT
        'Africa/Accra': '+0:00',          # GMT
        'Africa/Addis_Ababa': '+3:00',    # EAT
        'Africa/Algiers': '+1:00',        # CET
        'Africa/Asmara': '+3:00',         # EAT
        'Africa/Bamako': '+0:00',         # GMT
        'Africa/Bangui': '+1:00',         # WAT
        'Africa/Banjul': '+0:00',         # GMT
        'Africa/Bissau': '+0:00',         # GMT
        'Africa/Blantyre': '+2:00',       # CAT
        'Africa/Brazzaville': '+1:00',    # WAT
        'Africa/Bujumbura': '+2:00',      # CAT
        'Africa/Cairo': '+2:00',          # EET
        'Africa/Casablanca': '+1:00',     # +01
        'Africa/Ceuta': '+1:00',          # CET
        'Africa/Conakry': '+0:00',        # GMT
        'Africa/Dakar': '+0:00',          # GMT
        'Africa/Dar_es_Salaam': '+3:00',  # EAT
        'Africa/Djibouti': '+3:00',       # EAT
        'Africa/Douala': '+1:00',         # WAT
        'Africa/El_Aaiun': '+1:00',       # +01
        'Africa/Freetown': '+0:00',       # GMT
        'Africa/Gaborone': '+2:00',       # CAT
        'Africa/Harare': '+2:00',         # CAT
        'Africa/Johannesburg': '+2:00',   # SAST
        'Africa/Juba': '+2:00',           # CAT
        'Africa/Kampala': '+3:00',        # EAT
        'Africa/Khartoum': '+2:00',       # CAT
        'Africa/Kigali': '+2:00',         # CAT
        'Africa/Kinshasa': '+1:00',       # WAT
        'Africa/Lagos': '+1:00',          # WAT
        'Africa/Libreville': '+1:00',     # WAT
        'Africa/Lome': '+0:00',           # GMT
        'Africa/Luanda': '+1:00',         # WAT
        'Africa/Lubumbashi': '+2:00',     # CAT
        'Africa/Lusaka': '+2:00',         # CAT
        'Africa/Malabo': '+1:00',         # WAT
        'Africa/Maputo': '+2:00',         # CAT
        'Africa/Maseru': '+2:00',         # SAST
        'Africa/Mbabane': '+2:00',        # SAST
        'Africa/Mogadishu': '+3:00',      # EAT
        'Africa/Monrovia': '+0:00',       # GMT
        'Africa/Nairobi': '+3:00',        # EAT
        'Africa/Ndjamena': '+1:00',       # WAT
        'Africa/Niamey': '+1:00',         # WAT
        'Africa/Nouakchott': '+0:00',     # GMT
        'Africa/Ouagadougou': '+0:00',    # GMT
        'Africa/Porto-Novo': '+1:00',     # WAT
        'Africa/Sao_Tome': '+0:00',       # GMT
        'Africa/Tripoli': '+2:00',        # EET
        'Africa/Tunis': '+1:00',          # CET
        'Africa/Windhoek': '+2:00',       # CAT
        
        # America
        'America/Anchorage': '-9:00',     # AKST
        'America/Anguilla': '-4:00',      # AST
        'America/Antigua': '-4:00',       # AST
        'America/Araguaina': '-3:00',     # BRT
        'America/Argentina/Buenos_Aires': '-3:00',  # ART
        'America/Argentina/Catamarca': '-3:00',     # ART
        'America/Argentina/Cordoba': '-3:00',       # ART
        'America/Argentina/Jujuy': '-3:00',         # ART
        'America/Argentina/La_Rioja': '-3:00',      # ART
        'America/Argentina/Mendoza': '-3:00',       # ART
        'America/Argentina/Rio_Gallegos': '-3:00',  # ART
        'America/Argentina/Salta': '-3:00',         # ART
        'America/Argentina/San_Juan': '-3:00',      # ART
        'America/Argentina/San_Luis': '-3:00',      # ART
        'America/Argentina/Tucuman': '-3:00',       # ART
        'America/Argentina/Ushuaia': '-3:00',       # ART
        'America/Aruba': '-4:00',         # AST
        'America/Asuncion': '-3:00',      # PYT
        'America/Bahia': '-3:00',         # BRT
        'America/Bahia_Banderas': '-6:00', # CST
        'America/Barbados': '-4:00',      # AST
        'America/Belem': '-3:00',         # BRT
        'America/Belize': '-6:00',        # CST
        'America/Boa_Vista': '-4:00',     # AMT
        'America/Bogota': '-5:00',        # COT
        'America/Boise': '-7:00',         # MST
        'America/Campo_Grande': '-4:00',  # AMT
        'America/Cancun': '-5:00',        # EST
        'America/Caracas': '-4:00',       # VET
        'America/Cayenne': '-3:00',       # GFT
        'America/Cayman': '-5:00',        # EST
        'America/Chicago': '-6:00',       # CST
        'America/Chihuahua': '-7:00',     # MST
        'America/Ciudad_Juarez': '-7:00', # MST
        'America/Costa_Rica': '-6:00',    # CST
        'America/Coyhaique': '-3:00',     # CLST
        'America/Cuiaba': '-4:00',        # AMT
        'America/Curacao': '-4:00',       # AST
        'America/Dawson_Creek': '-7:00',  # MST
        'America/Denver': '-7:00',        # MST
        'America/Detroit': '-5:00',       # EST
        'America/Dominica': '-4:00',      # AST
        'America/Edmonton': '-7:00',      # MST
        'America/Eirunepe': '-5:00',      # ACT
        'America/El_Salvador': '-6:00',   # CST
        'America/Fortaleza': '-3:00',     # BRT
        'America/Glace_Bay': '-4:00',     # AST
        'America/Grand_Turk': '-5:00',    # EST
        'America/Grenada': '-4:00',       # AST
        'America/Guadeloupe': '-4:00',    # AST
        'America/Guatemala': '-6:00',     # CST
        'America/Guayaquil': '-5:00',     # ECT
        'America/Guyana': '-4:00',        # GYT
        'America/Halifax': '-4:00',       # AST
        'America/Havana': '-5:00',        # CST
        'America/Hermosillo': '-7:00',    # MST
        'America/Indiana/Indianapolis': '-5:00', # EST
        'America/Indiana/Vincennes': '-5:00',    # EST
        'America/Jamaica': '-5:00',       # EST
        'America/Juneau': '-9:00',        # AKST
        'America/Kentucky/Louisville': '-5:00',  # EST
        'America/Kralendijk': '-4:00',    # AST
        'America/La_Paz': '-4:00',        # BOT
        'America/Lima': '-5:00',          # PET
        'America/Los_Angeles': '-8:00',   # PST
        'America/Lower_Princes': '-4:00', # AST
        'America/Maceio': '-3:00',        # BRT
        'America/Managua': '-6:00',       # CST
        'America/Manaus': '-4:00',        # AMT
        'America/Marigot': '-4:00',       # AST
        'America/Martinique': '-4:00',    # AST
        'America/Matamoros': '-6:00',     # CST
        'America/Mazatlan': '-7:00',      # MST
        'America/Merida': '-6:00',        # CST
        'America/Mexico_City': '-6:00',   # CST
        'America/Miquelon': '-3:00',      # PMST
        'America/Moncton': '-4:00',       # AST
        'America/Monterrey': '-6:00',     # CST
        'America/Montevideo': '-3:00',    # UYT
        'America/Montserrat': '-4:00',    # AST
        'America/Nassau': '-5:00',        # EST
        'America/New_York': '-5:00',      # EST
        'America/North_Dakota/New_Salem': '-6:00', # CST
        'America/Nuuk': '-3:00',          # WGT
        'America/Ojinaga': '-7:00',       # MST
        'America/Panama': '-5:00',        # EST
        'America/Paramaribo': '-3:00',    # SRT
        'America/Phoenix': '-7:00',       # MST
        'America/Port_of_Spain': '-4:00', # AST
        'America/Port-au-Prince': '-5:00', # EST
        'America/Porto_Velho': '-4:00',   # AMT
        'America/Puerto_Rico': '-4:00',   # AST
        'America/Punta_Arenas': '-3:00',  # CLST
        'America/Recife': '-3:00',        # BRT
        'America/Regina': '-6:00',        # CST
        'America/Rio_Branco': '-5:00',    # ACT
        'America/Santarem': '-3:00',      # BRT
        'America/Santiago': '-3:00',      # CLST
        'America/Santo_Domingo': '-4:00', # AST
        'America/Sao_Paulo': '-3:00',     # BRT
        'America/St_Barthelemy': '-4:00', # AST
        'America/St_Johns': '-3:30',      # NST
        'America/St_Kitts': '-4:00',      # AST
        'America/St_Lucia': '-4:00',      # AST
        'America/St_Thomas': '-4:00',     # AST
        'America/St_Vincent': '-4:00',    # AST
        'America/Swift_Current': '-6:00', # CST
        'America/Tegucigalpa': '-6:00',   # CST
        'America/Tijuana': '-8:00',       # PST
        'America/Toronto': '-5:00',       # EST
        'America/Tortola': '-4:00',       # AST
        'America/Vancouver': '-8:00',     # PST
        'America/Whitehorse': '-8:00',    # PST
        'America/Winnipeg': '-6:00',      # CST
        
        # Arctic
        'Arctic/Longyearbyen': '+1:00',   # CET
        
        # Asia
        'Asia/Aden': '+3:00',             # AST
        'Asia/Almaty': '+6:00',           # ALMT
        'Asia/Amman': '+2:00',            # EET
        'Asia/Anadyr': '+12:00',          # ANAT
        'Asia/Aqtau': '+5:00',            # AQTT
        'Asia/Aqtobe': '+5:00',           # AQTT
        'Asia/Ashgabat': '+5:00',         # TMT
        'Asia/Atyrau': '+5:00',           # AQTT
        'Asia/Baghdad': '+3:00',          # AST
        'Asia/Bahrain': '+3:00',          # AST
        'Asia/Baku': '+4:00',             # AZT
        'Asia/Bangkok': '+7:00',          # ICT
        'Asia/Barnaul': '+7:00',          # KRAT
        'Asia/Beirut': '+2:00',           # EET
        'Asia/Bishkek': '+6:00',          # KGT
        'Asia/Brunei': '+8:00',           # BNT
        'Asia/Chita': '+9:00',            # YAKT
        'Asia/Colombo': '+5:30',          # IST
        'Asia/Damascus': '+2:00',         # EET
        'Asia/Dhaka': '+6:00',            # BST
        'Asia/Dili': '+9:00',             # TLT
        'Asia/Dubai': '+4:00',            # GST
        'Asia/Dushanbe': '+5:00',         # TJT
        'Asia/Famagusta': '+2:00',        # EET
        'Asia/Gaza': '+2:00',             # EET
        'Asia/Hebron': '+2:00',           # EET
        'Asia/Ho_Chi_Minh': '+7:00',      # ICT
        'Asia/Hong_Kong': '+8:00',        # HKT
        'Asia/Hovd': '+7:00',             # HOVT
        'Asia/Irkutsk': '+8:00',          # IRKT
        'Asia/Jakarta': '+7:00',          # WIB
        'Asia/Jayapura': '+9:00',         # WIT
        'Asia/Jerusalem': '+2:00',        # IST
        'Asia/Kabul': '+4:30',            # AFT
        'Asia/Kamchatka': '+12:00',       # PETT
        'Asia/Karachi': '+5:00',          # PKT
        'Asia/Kathmandu': '+5:45',        # NPT
        'Asia/Kolkata': '+5:30',          # IST
        'Asia/Krasnoyarsk': '+7:00',      # KRAT
        'Asia/Kuala_Lumpur': '+8:00',     # MYT
        'Asia/Kuching': '+8:00',          # MYT
        'Asia/Kuwait': '+3:00',           # AST
        'Asia/Macau': '+8:00',            # CST
        'Asia/Magadan': '+11:00',         # MAGT
        'Asia/Makassar': '+8:00',         # WITA
        'Asia/Manila': '+8:00',           # PHT
        'Asia/Muscat': '+4:00',           # GST
        'Asia/Nicosia': '+2:00',          # EET
        'Asia/Novokuznetsk': '+7:00',     # KRAT
        'Asia/Novosibirsk': '+7:00',      # NOVT
        'Asia/Omsk': '+6:00',             # OMST
        'Asia/Oral': '+5:00',             # ORAT
        'Asia/Phnom_Penh': '+7:00',       # ICT
        'Asia/Pontianak': '+7:00',        # WIB
        'Asia/Pyongyang': '+9:00',        # KST
        'Asia/Qatar': '+3:00',            # AST
        'Asia/Qostanay': '+6:00',         # QYZT
        'Asia/Qyzylorda': '+5:00',        # QYZT
        'Asia/Riyadh': '+3:00',           # AST
        'Asia/Sakhalin': '+11:00',        # SAKT
        'Asia/Samarkand': '+5:00',        # UZT
        'Asia/Seoul': '+9:00',            # KST
        'Asia/Shanghai': '+8:00',         # CST
        'Asia/Singapore': '+8:00',        # SGT
        'Asia/Taipei': '+8:00',           # CST
        'Asia/Tashkent': '+5:00',         # UZT
        'Asia/Tbilisi': '+4:00',          # GET
        'Asia/Tehran': '+3:30',           # IRST
        'Asia/Thimphu': '+6:00',          # BTT
        'Asia/Tokyo': '+9:00',            # JST
        'Asia/Tomsk': '+7:00',            # TOMST
        'Asia/Ulaanbaatar': '+8:00',      # ULAT
        'Asia/Urumqi': '+6:00',           # XJT
        'Asia/Vientiane': '+7:00',        # ICT
        'Asia/Vladivostok': '+10:00',     # VLAT
        'Asia/Yakutsk': '+9:00',          # YAKT
        'Asia/Yangon': '+6:30',           # MMT
        'Asia/Yekaterinburg': '+5:00',    # YEKT
        'Asia/Yerevan': '+4:00',          # AMT
        
        # Atlantic
        'Atlantic/Azores': '-1:00',       # AZOT
        'Atlantic/Bermuda': '-4:00',      # AST
        'Atlantic/Canary': '+0:00',       # WET
        'Atlantic/Cape_Verde': '-1:00',   # CVT
        'Atlantic/Faroe': '+0:00',        # WET
        'Atlantic/Madeira': '+0:00',      # WET
        'Atlantic/Reykjavik': '+0:00',    # GMT
        'Atlantic/South_Georgia': '-2:00', # GST
        'Atlantic/St_Helena': '+0:00',    # GMT
        'Atlantic/Stanley': '-3:00',      # FKST
        
        # Australia
        'Australia/Adelaide': '+9:30',    # ACST
        'Australia/Brisbane': '+10:00',   # AEST
        'Australia/Broken_Hill': '+9:30', # ACST
        'Australia/Darwin': '+9:30',      # ACST
        'Australia/Hobart': '+10:00',     # AEST
        'Australia/Melbourne': '+10:00',  # AEST
        'Australia/Perth': '+8:00',       # AWST
        'Australia/Sydney': '+10:00',     # AEST
        
        # Europe
        'Europe/Amsterdam': '+1:00',      # CET
        'Europe/Andorra': '+1:00',        # CET
        'Europe/Astrakhan': '+4:00',      # +04
        'Europe/Athens': '+2:00',         # EET
        'Europe/Belgrade': '+1:00',       # CET
        'Europe/Berlin': '+1:00',         # CET
        'Europe/Bratislava': '+1:00',     # CET
        'Europe/Brussels': '+1:00',       # CET
        'Europe/Bucharest': '+2:00',      # EET
        'Europe/Budapest': '+1:00',       # CET
        'Europe/Chisinau': '+2:00',       # EET
        'Europe/Copenhagen': '+1:00',     # CET
        'Europe/Dublin': '+0:00',         # GMT
        'Europe/Gibraltar': '+1:00',      # CET
        'Europe/Guernsey': '+0:00',       # GMT
        'Europe/Helsinki': '+2:00',       # EET
        'Europe/Isle_of_Man': '+0:00',    # GMT
        'Europe/Istanbul': '+3:00',       # TRT
        'Europe/Jersey': '+0:00',         # GMT
        'Europe/Kaliningrad': '+2:00',    # EET
        'Europe/Kirov': '+3:00',          # +03
        'Europe/Kyiv': '+2:00',           # EET
        'Europe/Lisbon': '+0:00',         # WET
        'Europe/Ljubljana': '+1:00',      # CET
        'Europe/London': '+0:00',         # GMT
        'Europe/Luxembourg': '+1:00',     # CET
        'Europe/Madrid': '+1:00',         # CET
        'Europe/Malta': '+1:00',          # CET
        'Europe/Mariehamn': '+2:00',      # EET
        'Europe/Minsk': '+3:00',          # +03
        'Europe/Monaco': '+1:00',         # CET
        'Europe/Moscow': '+3:00',         # MSK
        'Europe/Oslo': '+1:00',           # CET
        'Europe/Paris': '+1:00',          # CET
        'Europe/Podgorica': '+1:00',      # CET
        'Europe/Prague': '+1:00',         # CET
        'Europe/Riga': '+2:00',           # EET
        'Europe/Rome': '+1:00',           # CET
        'Europe/Samara': '+4:00',         # +04
        'Europe/San_Marino': '+1:00',     # CET
        'Europe/Sarajevo': '+1:00',       # CET
        'Europe/Saratov': '+4:00',        # +04
        'Europe/Simferopol': '+3:00',     # MSK
        'Europe/Skopje': '+1:00',         # CET
        'Europe/Sofia': '+2:00',          # EET
        'Europe/Stockholm': '+1:00',      # CET
        'Europe/Tallinn': '+2:00',        # EET
        'Europe/Tirane': '+1:00',         # CET
        'Europe/Ulyanovsk': '+4:00',      # +04
        'Europe/Vaduz': '+1:00',          # CET
        'Europe/Vatican': '+1:00',        # CET
        'Europe/Vienna': '+1:00',         # CET
        'Europe/Vilnius': '+2:00',        # EET
        'Europe/Volgograd': '+3:00',      # +03
        'Europe/Warsaw': '+1:00',         # CET
        'Europe/Zagreb': '+1:00',         # CET
        'Europe/Zurich': '+1:00',         # CET
        
        # Indian
        'Indian/Antananarivo': '+3:00',   # EAT
        'Indian/Christmas': '+7:00',      # CXT
        'Indian/Cocos': '+6:30',          # CCT
        'Indian/Comoro': '+3:00',         # EAT
        'Indian/Kerguelen': '+5:00',      # TFT
        'Indian/Mahe': '+4:00',           # SCT
        'Indian/Maldives': '+5:00',       # MVT
        'Indian/Mauritius': '+4:00',      # MUT
        'Indian/Mayotte': '+3:00',        # EAT
        'Indian/Reunion': '+4:00',        # RET
        
        # Pacific
        'Pacific/Apia': '+13:00',         # WSST
        'Pacific/Auckland': '+12:00',     # NZST
        'Pacific/Bougainville': '+11:00', # BST
        'Pacific/Efate': '+11:00',        # VUT
        'Pacific/Fiji': '+12:00',         # FJT
        'Pacific/Funafuti': '+12:00',     # TVT
        'Pacific/Guadalcanal': '+11:00',  # SBT
        'Pacific/Guam': '+10:00',         # ChST
        'Pacific/Honolulu': '-10:00',     # HST
        'Pacific/Majuro': '+12:00',       # MHT
        'Pacific/Nauru': '+12:00',        # NRT
        'Pacific/Niue': '-11:00',         # NUT
        'Pacific/Norfolk': '+11:00',      # NFT
        'Pacific/Noumea': '+11:00',       # NCT
        'Pacific/Pago_Pago': '-11:00',    # SST
        'Pacific/Palau': '+9:00',         # PWT
        'Pacific/Pitcairn': '-8:00',      # PST
        'Pacific/Pohnpei': '+11:00',      # PONT
        'Pacific/Port_Moresby': '+10:00', # PGT
        'Pacific/Rarotonga': '-10:00',    # CKT
        'Pacific/Saipan': '+10:00',       # ChST
        'Pacific/Tahiti': '-10:00',       # TAHT
        'Pacific/Tarawa': '+12:00',       # GILT
        'Pacific/Tongatapu': '+13:00',    # TOT
        'Pacific/Wallis': '+12:00',       # WFT
    }

