# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .automations_list_response_item_status import AutomationsListResponseItemStatus
from .automations_list_response_item_trigger import AutomationsListResponseItemTrigger
from .automations_list_response_item_workflow_item import AutomationsListResponseItemWorkflowItem


class AutomationsListResponseItem(UncheckedBaseModel):
    id: str
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    trigger: AutomationsListResponseItemTrigger
    workflow: typing.List[AutomationsListResponseItemWorkflowItem]
    status: AutomationsListResponseItemStatus
    created: dt.datetime
    updated: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
