# coding: utf-8

"""
    Electricity Maps API

    Electricity Maps API

    The version of the OpenAPI document: 1.0.0
    Contact: hello@electricitymaps.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi.models.emission_factor_type import EmissionFactorType
from openapi.models.temporal_granularity import TemporalGranularity
from typing import Optional, Set
from typing_extensions import Self

class CarbonIntensity(BaseModel):
    """
    CarbonIntensity
    """ # noqa: E501
    zone: StrictStr
    carbon_intensity: Union[StrictFloat, StrictInt] = Field(description="The carbon intensity in gCO2eq/kWh.", alias="carbonIntensity")
    dt: StrictStr = Field(description="The datetime of the data.", alias="datetime")
    updated_at: StrictStr = Field(description="The datetime of the last update of this specific data point.", alias="updatedAt")
    emission_factor_type: EmissionFactorType = Field(alias="emissionFactorType")
    is_estimated: StrictBool = Field(description="Whether the data is estimated.", alias="isEstimated")
    estimation_method: Optional[StrictStr] = Field(description="If the data is estimated, the method used to estimate the data.", alias="estimationMethod")
    temporal_granularity: Optional[TemporalGranularity] = Field(default=None, alias="temporalGranularity")
    __properties: ClassVar[List[str]] = ["zone", "carbonIntensity", "datetime", "updatedAt", "emissionFactorType", "isEstimated", "estimationMethod", "temporalGranularity"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CarbonIntensity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if estimation_method (nullable) is None
        # and model_fields_set contains the field
        if self.estimation_method is None and "estimation_method" in self.model_fields_set:
            _dict['estimationMethod'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CarbonIntensity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "zone": obj.get("zone"),
            "carbonIntensity": obj.get("carbonIntensity"),
            "datetime": obj.get("datetime"),
            "updatedAt": obj.get("updatedAt"),
            "emissionFactorType": obj.get("emissionFactorType"),
            "isEstimated": obj.get("isEstimated"),
            "estimationMethod": obj.get("estimationMethod"),
            "temporalGranularity": obj.get("temporalGranularity")
        })
        return _obj


