# coding: utf-8

"""
Identity Provider - Admin API

Admin API endpoints (public tenant only)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from binoauth.admin.models.management_token_response import ManagementTokenResponse


class TestManagementTokenResponse(unittest.TestCase):
    """ManagementTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManagementTokenResponse:
        """Test ManagementTokenResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ManagementTokenResponse`
        """
        model = ManagementTokenResponse()
        if include_optional:
            return ManagementTokenResponse(
                user = binoauth.admin.models.management_user_response.ManagementUserResponse(
                    id = null,
                    email = '',
                    role = '',
                    image = '',
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                access_token = '',
                refresh_token = '',
                access_token_type = 'bearer',
                access_token_expires = 56,
                refresh_token_expires = 56
            )
        else:
            return ManagementTokenResponse(
                user = binoauth.admin.models.management_user_response.ManagementUserResponse(
                    id = null,
                    email = '',
                    role = '',
                    image = '',
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                access_token = '',
        )
        """

    def testManagementTokenResponse(self):
        """Test ManagementTokenResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
