
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-08-12T16:39:32+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "df666766edc9f646d9064cedd7c841d58fa67a46",
 "version": "5.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
