# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ChatFhirClientConfig(UniversalBaseModel):
    """
    User-specific FHIR configuration overrides for chat requests
    """

    on_behalf_of_email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Override email for On-Behalf-Of requests (Medplum only)
    """

    instance_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Override instance name for multi-instance providers
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
