from functools import cache

@cache
def decompose_prime(p: int) -> tuple[int, int]: ...
def decompose_number(n: dict | int, check_count: int | None = None, *, limited_checks: bool = False) -> set[tuple[int, int]]: ...
