from __future__ import annotations
from typing import List, Dict, Any, Optional, Protocol

class MemoryBase(Protocol):
    def remember(self, event: Dict[str, Any]) -> None: ...
    def recall(self, n: int = 10) -> List[Dict[str, Any]]: ...
    def clear(self) -> None: ...
    def summarize(self, n: int = 20, max_chars: int = 1200) -> str: ...
