"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from que_media.types import BaseModel
from typing_extensions import TypedDict


class PresignResponseTypedDict(TypedDict):
    r"""A presigned URL that can be used for a temporary, authenticated upload to S3."""

    url: str
    r"""The presigned S3 URL to which the client should PUT the asset file."""
    key: str
    r"""The S3 object key that the asset will have after being uploaded. This key should be used in subsequent API calls."""


class PresignResponse(BaseModel):
    r"""A presigned URL that can be used for a temporary, authenticated upload to S3."""

    url: str
    r"""The presigned S3 URL to which the client should PUT the asset file."""

    key: str
    r"""The S3 object key that the asset will have after being uploaded. This key should be used in subsequent API calls."""
