AGENTS = [
  "AI2Bot",
  "AddSearchBot",
  "Ai2Bot-Dolma",
  "Amazonbot",
  "Andibot",
  "Applebot",
  "Applebot-Extended",
  "Awario",
  "Brightbot 1.0",
  "Bytespider",
  "CCBot",
  "ChatGPT Agent",
  "ChatGPT-User",
  "Claude-SearchBot",
  "Claude-User",
  "Claude-Web",
  "ClaudeBot",
  "CloudVertexBot",
  "Cotoyogi",
  "Crawlspace",
  "Datenbank Crawler",
  "Devin",
  "Diffbot",
  "DuckAssistBot",
  "Echobot Bot",
  "EchoboxBot",
  "FacebookBot",
  "Factset_spyderbot",
  "FirecrawlAgent",
  "FriendlyCrawler",
  "GPTBot",
  "Gemini-Deep-Research",
  "Google-CloudVertexBot",
  "Google-Extended",
  "GoogleAgent-Mariner",
  "GoogleOther",
  "GoogleOther-Image",
  "GoogleOther-Video",
  "ICC-Crawler",
  "ISSCyberRiskCrawler",
  "ImagesiftBot",
  "Kangaroo Bot",
  "LinerBot",
  "Meta-ExternalAgent",
  "Meta-ExternalFetcher",
  "MistralAI-User",
  "MistralAI-User/1.0",
  "MyCentralAIScraperBot",
  "NovaAct",
  "OAI-SearchBot",
  "OpenAI",
  "Operator",
  "PanguBot",
  "Panscient",
  "Perplexity-User",
  "PerplexityBot",
  "PetalBot",
  "PhindBot",
  "Poseidon Research Crawler",
  "QualifiedBot",
  "QuillBot",
  "SBIntuitionsBot",
  "Scrapy",
  "SemrushBot-OCOB",
  "SemrushBot-SWA",
  "Sidetrade indexer bot",
  "Thinkbot",
  "TikTokSpider",
  "Timpibot",
  "VelenPublicWebCrawler",
  "WARDBot",
  "Webzio-Extended",
  "YaK",
  "YandexAdditional",
  "YandexAdditionalBot",
  "YouBot",
  "aiHitBot",
  "anthropic-ai",
  "bedrockbot",
  "bigsur.ai",
  "cohere-ai",
  "cohere-training-data-crawler",
  "facebookexternalhit",
  "iaskspider/2.0",
  "img2dataset",
  "meta-externalagent",
  "meta-externalfetcher",
  "netEstate Imprint Crawler",
  "omgili",
  "omgilibot",
  "panscient.com",
  "quillbot.com",
  "wpbot"
]
