# coding: utf-8

"""
CxO Bot Automation API

 CxO Bot Automation API manages the CxO automation platform.  ## Workflows  A CxO Workflow defines the overall flow of AI automated tasks.  Conceptually, a Workflow is a sequence of steps. Those steps are defined by advanced AI units, known as Agents, and are carried out by performing detailed actions, resulting in a execution run.  ## Schedules  CxO Schedules are features allowing you to execute specific CxO Workflows at specified times or intervals.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from adomo.api.api_service_api import ApiServiceApi


class TestApiServiceApi(unittest.TestCase):
    """ApiServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiServiceApi()

    def tearDown(self) -> None:
        pass

    def test_health_check_health_get(self) -> None:
        """Test case for health_check_health_get

        Health Check
        """
        pass

    def test_metrics_metrics_get(self) -> None:
        """Test case for metrics_metrics_get

        Metrics
        """
        pass


if __name__ == "__main__":
    unittest.main()
