# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import typing_extensions
from ..types.media_list_response_item_kind import MediaListResponseItemKind
from .media_list_response_item_files_item import MediaListResponseItemFilesItemParams


class MediaListResponseItemParams(typing_extensions.TypedDict):
    id: str
    object: str
    kind: typing_extensions.NotRequired[MediaListResponseItemKind]
    title: typing_extensions.NotRequired[str]
    alt: typing_extensions.NotRequired[str]
    width: typing_extensions.NotRequired[int]
    height: typing_extensions.NotRequired[int]
    duration: typing_extensions.NotRequired[float]
    files: typing.Sequence[MediaListResponseItemFilesItemParams]
    urls: typing.Dict[str, typing.Optional[typing.Any]]
    background: typing_extensions.NotRequired[str]
    metadata: typing_extensions.NotRequired[typing.Dict[str, typing.Optional[typing.Any]]]
    created: dt.datetime
    updated: dt.datetime
