"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .redisconnectionlimits import RedisConnectionLimits, RedisConnectionLimitsTypedDict
from cribl_control_plane.types import BaseModel
from typing_extensions import TypedDict


class RedisLimitsTypedDict(TypedDict):
    connections: RedisConnectionLimitsTypedDict


class RedisLimits(BaseModel):
    connections: RedisConnectionLimits
