"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpgradeGroupSettingsTypedDict(TypedDict):
    is_rolling: NotRequired[bool]
    quantity: NotRequired[float]
    retry_count: NotRequired[float]
    retry_delay: NotRequired[float]


class UpgradeGroupSettings(BaseModel):
    is_rolling: Annotated[Optional[bool], pydantic.Field(alias="isRolling")] = None

    quantity: Optional[float] = None

    retry_count: Annotated[Optional[float], pydantic.Field(alias="retryCount")] = None

    retry_delay: Annotated[Optional[float], pydantic.Field(alias="retryDelay")] = None
