# Generated by ariadne-codegen
# Source: /app/operations

from typing import Optional

from .base_model import BaseModel


class UserFromToken(BaseModel):
    user_from_token: Optional["UserFromTokenUserFromToken"]


class UserFromTokenUserFromToken(BaseModel):
    id: str
    full_name: Optional[str]


UserFromToken.model_rebuild()
