#  Developed by CQ Inversiones SAS. Copyright ©. 2019-2025. All rights reserved.
#  Desarrollado por CQ Inversiones SAS. Copyright ©. 2019-2025. Todos los derechos reservados.

# Generated by Django 5.1.5 on 2025-02-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zb_repository', '0003_category_file_fileextended_filetables_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='enabled',
        ),
    ]
