#  Developed by CQ Inversiones SAS. Copyright ©. 2019-2025. All rights reserved.
#  Desarrollado por CQ Inversiones SAS. Copyright ©. 2019-2025. Todos los derechos reservados.

# Generated by Django 5.1.5 on 2025-03-18 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zb_repository', '0004_remove_category_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.IntegerField(default=0, editable=False, help_text='Level of category.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Level'),
        ),
    ]
