# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .additional_card_details import AdditionalCardDetails
from .card_issuer import CardIssuer
from .card_issuer_country import CardIssuerCountry


class CardDetails(UniversalBaseModel):
    bin: typing.Optional[str] = None
    last4: typing.Optional[str] = None
    expiration_month: typing.Optional[int] = None
    expiration_year: typing.Optional[int] = None
    brand: typing.Optional[str] = None
    funding: typing.Optional[str] = None
    authentication: typing.Optional[str] = None
    issuer: typing.Optional[CardIssuer] = None
    issuer_country: typing.Optional[CardIssuerCountry] = None
    segment: typing.Optional[str] = None
    additional: typing.Optional[typing.List[AdditionalCardDetails]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
