# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .proxy_transform_options import ProxyTransformOptions


class ProxyTransform(UniversalBaseModel):
    type: typing.Optional[str] = None
    code: typing.Optional[str] = None
    matcher: typing.Optional[str] = None
    expression: typing.Optional[str] = None
    replacement: typing.Optional[str] = None
    options: typing.Optional[ProxyTransformOptions] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
