# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.2.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from conekta.api.balances_api import BalancesApi


class TestBalancesApi(unittest.TestCase):
    """BalancesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BalancesApi()

    def tearDown(self) -> None:
        pass

    def test_get_balance(self) -> None:
        """Test case for get_balance

        Get a company's balance
        """
        pass


if __name__ == '__main__':
    unittest.main()
